Feature/pn 2021
pagopa/pn-hub-spid-login-aws pull request #17
Opened 2022-11-04 11:47 UTC by fdammassa

Custom rule to serve metadata file on `/metadata` path via a lambda reading from s3.

@MTurraPpa @marco-vit-pagopa metadata file for hotfix env in the bucket `spidhub-hotfix-eu-south-1-spid` is `metadata/metadata-signed.xml`.

2022-11-04 12:37 UTC, marco-vit-pagopa requested changes
Aggiunta log group per la lambda con retention di 14gg

2022-11-04 12:37 UTC, marco-vit-pagopa commented on scripts/deploy/stacks/custom-metadata.yaml
> +  CustomMetadataLambda:
Potresti aggiungere un log group per questa lambda (con retention di 14 gg)

2022-11-04 13:49 UTC, fdammassa commented on scripts/deploy/stacks/custom-metadata.yaml
> +  CustomMetadataLambda:
@marco-vit-pagopa dichiarato esplicitamente il loggroup con retention a 14 giorni

2022-11-07 16:04 UTC, marco-vit-pagopa approved these changes

2022-11-07 16:06 UTC, merged